version: '3.7'

services:

  db:
    # In production, you may want to use a managed database service
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: userdb
      # You should definitely change the password in production
      MYSQL_PASSWORD: psw
    volumes:
      - db-data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
    ports:
      - '3306:3306'
      
  adminer:
    image: adminer
    restart: always
    ports:
      - '8999:8080'
      
    mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
